#!/usr/bin/env sh

down() {
  pamixer -d 5
  volume=$(pamixer --get-volume)
  notify-send -a "VOLUME" "Decreasing to $volume%" -h int:value:"$volume" -i audio-volume-low-symbolic -r 2593 -u normal
}

up() {
  pamixer -i 5
  volume=$(pamixer --get-volume)
  notify-send -a "VOLUME" "Increasing to $volume%" -h int:value:"$volume" -i audio-volume-high-symbolic -r 2593 -u normal
}

mute() {
  muted=$(pamixer --get-mute)

  if $muted; then
    pamixer -u
    notify-send -a "VOLUME" "Unmuted" -i audio-volume-high-symbolic -r 2593 -u normal
  else
    pamixer -m
    notify-send -a "VOLUME" "Muted" -i audio-volume-muted-symbolic -r 2593 -u normal
  fi
}

case "$1" in
  up) up;;
  down) down;;
  mute) mute;;
esac
